### ISSUE TITLE
Editing a todo item

### ISSUE THREAD

**Issue by mherman22** [mherman22/todo-typescript#6]
currently doesnt do that

**Comment by rameshchandra8520** [comment]
Hi @mherman22, Editing a task option is currently working.

![image](https://github.com/mherman22/todo-typescript/assets/114871196/f6437b85-c3f9-4206-adae-ab591f3ae66d)
![image](https://github.com/mherman22/todo-typescript/assets/114871196/3262ed2f-b1a2-4108-8ed4-d85a9f2cc770)
![image](https://github.com/mherman22/todo-typescript/assets/114871196/58abffd8-27b8-4b7e-b37b-94b95c5a841f)
